import type { Member, Publication, VideoCategory, Video, News, Activity, SiteSettings } from '@/types';

// ============================================================================
// STATIC DATABASE - Edit this file to update data
// ============================================================================

export const members: Member[] = [
  {
    id: 'member_1',
    name: 'Dr. Arturo Rodríguez',
    role: 'Líder del Proyecto',
    orcid: '0000-0002-7017-9443',
    email: 'arturo.rodriguez@uleam.edu.ec',
    photo: '/images/lider_arturo_rodriguez.jpg',
    is_leader: true,
    order: 1,
    created: '2025-01-01T00:00:00Z',
    updated: '2025-01-01T00:00:00Z',
  },
  {
    id: 'member_2',
    name: 'Dr. Jhonny Villafuerte',
    role: 'Colíder del Proyecto',
    orcid: '0000-0001-6053-6307',
    email: 'jhonny.villafuerte@uleam.edu.ec',
    photo: '/images/colider_Jhonny_Villafuerte.jpg',
    is_leader: false,
    order: 2,
    created: '2025-01-01T00:00:00Z',
    updated: '2025-01-01T00:00:00Z',
  },
  {
    id: 'member_3',
    name: 'Mg. Cristina Basantes',
    role: 'Coordinadora de Productos Educomunicacionales',
    orcid: '0000-0001-5184-9643',
    email: '',
    photo: '/images/Cristina_CoordinadorPODCAST.jpeg',
    is_leader: false,
    order: 3,
    created: '2025-01-01T00:00:00Z',
    updated: '2025-01-01T00:00:00Z',
  },
  {
    id: 'member_4',
    name: 'Psi. Johana Bello, Mg.',
    role: 'Coordinadora de Internacionalización',
    orcid: '0000-0002-0882-1060',
    email: '',
    photo: '/images/JohanaBello.jpeg',
    is_leader: false,
    order: 4,
    created: '2025-01-01T00:00:00Z',
    updated: '2025-01-01T00:00:00Z',
  },
  {
    id: 'member_5',
    name: 'Andy Castillo',
    role: 'Estudiante Investigador',
    orcid: '0009-0009-8630-7444',
    email: '',
    photo: '/images/ANdyCastilo.png',
    is_leader: false,
    order: 5,
    created: '2026-04-26T00:00:00Z',
    updated: '2026-04-26T00:00:00Z',
  },
  {
    id: 'member_6',
    name: 'Josselyn Mera Rivas',
    role: 'Estudiante Investigadora / Equipo de Podcast',
    orcid: '',
    email: '',
    photo: '/images/Josselyn_Mera.jpg',
    is_leader: false,
    order: 6,
    created: '2026-05-20T00:00:00Z',
    updated: '2026-05-27T00:00:00Z',
  },
  {
    id: 'member_7',
    name: 'Doménica Valeska Vélez Bravo',
    role: 'Equipo de Podcast',
    orcid: '0009-0009-3023-0564',
    email: '',
    photo: '/images/Domenica_Velez.jpeg',
    is_leader: false,
    order: 8,
    created: '2026-05-27T00:00:00Z',
    updated: '2026-05-27T00:00:00Z',
  },
  {
    id: 'member_8',
    name: 'Ailys Jordana Bailón Borja',
    role: 'Estudiante Investigadora / Equipo de Podcast',
    orcid: '',
    email: '',
    photo: '/images/Ailys_Bailon.jpeg',
    is_leader: false,
    order: 7,
    created: '2026-05-29T00:00:00Z',
    updated: '2026-05-29T00:00:00Z',
  },
];

export const publications: Publication[] = [
  {
    id: 'pub_3',
    title: 'Innovaciones Educativas: Experiencias de vinculación social, prácticas preprofesionales, proyectos de investigación',
    authors: 'Villafuerte-Holguín, J., Quijije, G. A., Bello Piguave, J. E., Rivera, A. T. (Eds.)',
    abstract: 'Compilación de experiencias académicas en vinculación social, prácticas preprofesionales e investigación, co-publicada por RED LEA, ULEAM, UTEG y Universidad de Concepción del Uruguay. ISBN 978-9942-614-37-7.',
    publication_date: '2026-04-20',
    doi_link: 'https://doi.org/10.47189/book20260420',
    pdf_file: '/files/Libro-Innovaciones-Educativas.pdf',
    type: 'book',
    category: 'libros',
    created: '2026-04-20T00:00:00Z',
    updated: '2026-04-20T00:00:00Z',
  },
  {
    id: 'pub_62',
    title: 'Total Physical Response as a strategy to improve the speaking skills of beginners EFL students in a rural Ecuadorian school',
    authors: 'Rivera Parrales, E. M., Rodríguez Zambrano, A. D.',
    abstract: 'Investigación sobre la estrategia Total Physical Response (TPR) para mejorar las habilidades orales de estudiantes principiantes de inglés como lengua extranjera en una escuela rural ecuatoriana.',
    publication_date: '2026-04-01',
    doi_link: 'https://doi.org/10.59155/is.v9i2.375',
    type: 'article',
    category: 'regional',
    created: '2026-04-01T00:00:00Z',
    updated: '2026-04-01T00:00:00Z',
  },
  {
    id: 'pub_60',
    title: 'Microenseñanza con tecnologías emergentes para el mejoramiento de la macrodestreza lingüística de la expresión oral',
    authors: 'Rodríguez Zambrano, A. D. et al.',
    abstract: 'Estudio sobre el uso de la microenseñanza combinada con tecnologías emergentes como estrategia para fortalecer la expresión oral en el aula. Publicado en Revista Científica Multidisciplinar, 10(1), 7709–7729.',
    publication_date: '2026-03-01',
    doi_link: 'https://doi.org/10.37811/cl_rcm.v10i1.22852',
    type: 'article',
    category: 'regional',
    created: '2026-03-01T00:00:00Z',
    updated: '2026-03-01T00:00:00Z',
  },
  {
    id: 'pub_58',
    title: 'Comparación del nivel de lectura funcional en estudiantes de segundo y cuarto grado de E.G.B.',
    authors: 'Rodríguez Zambrano, A. D. et al.',
    abstract: 'Análisis comparativo del nivel de lectura funcional entre estudiantes de segundo y cuarto grado de Educación General Básica. Publicado en Revista Científica Cumbres, Vol. 11(2).',
    publication_date: '2026-03-01',
    doi_link: 'http://doi.org/10.48190/cumbres.v11n2a9',
    type: 'article',
    category: 'regional',
    created: '2026-03-01T00:00:00Z',
    updated: '2026-03-01T00:00:00Z',
  },
  {
    id: 'pub_61',
    title: 'Identifying the Main Determinants of Low Student Interaction in English Speaking Classes as a Foreign Language in Ecuador',
    authors: 'Intriago Chamba, E. I., Rodríguez Zambrano, A. D., & Sánchez Olivo, D. A.',
    abstract: 'Estudio sobre las principales causas de la baja interacción estudiantil en clases de expresión oral en inglés como lengua extranjera. Publicado en Ciencia y Reflexión, Revista Multidisciplinaria, 5(1). En prensa.',
    publication_date: '2026-06-01',
    type: 'article',
    category: 'regional',
    doi_link: 'https://cienciayreflexion.org/index.php/Revista/article/view/1036',
    created: '2026-04-26T00:00:00Z',
    updated: '2026-04-26T00:00:00Z',
  },
  {
    id: 'pub_63',
    title: 'Transition from Regular English Instruction to Bilingual Education: An Experience Using Gamification',
    authors: 'Piloso-Cedeño, J. P., & Villafuerte-Holguin, J.',
    abstract: 'Education Quarterly Reviews, 8(2), 159-171. ISSN 2621-5799.',
    publication_date: '2025-01-01',
    doi_link: 'https://doi.org/10.31014/aior.1993.08.02.588',
    type: 'article',
    category: 'regional',
    created: '2026-04-27T00:00:00Z',
    updated: '2026-06-09T00:00:00Z',
  },
  {
    id: 'pub_64',
    title: 'Podcast: An educational innovation in foreign Languages instruction',
    authors: 'Villafuerte-Holguín, J., Cevallos Zambrano, D. P., Rodríguez Zambrano, A. D., Escalantes Delgado, J. N., Bailón Delgado, O. E., Guaranda Paredes, F. D., Calderón Pino, C. V., Palma Cedeño, N. N., Macías Mendoza, A. F., Mendoza García, K. M., Mendoza Palma, J. A., Moreno Álava, K. J., Quiroz Velásquez, J. M., Carranza Coronel, E. J., Piloso Cedeño, J. P., Lorente Tello, S. A., Barcia Espinales, M. A.',
    abstract: 'Resultado de la integración de tres proyectos de investigación: (1) Innovación educativa a través de podcast: Impacto en el Aprendizaje de Estudiantes Universitarios con Enfoque de Género y (2) Innovaciones pedagógicas e internacionalización de la formación de docentes para el desarrollo humano y sostenible, ambos desarrollados en la carrera de Pedagogía de los Idiomas Nacionales y Extranjeros (PINE) de la Universidad Laica Eloy Alfaro de Manabí. Estudiantes y docentes investigaron los aportes del podcast a procesos de enseñanza innovadores en el contexto universitario, con un enfoque multidisciplinario e integral. Editorial: Ediciones ULEAM.',
    publication_date: '2026-01-01',
    pdf_file: '/files/Libro-Podcast-Educacion-Innovadora.pdf',
    type: 'book',
    category: 'libros',
    created: '2026-06-07T00:00:00Z',
    updated: '2026-06-07T00:00:00Z',
  },
  {
    id: 'pub_65',
    title: 'Use of Podcasts for Leadership and Emotional Intelligence Development: A Review Study',
    authors: 'Quiroz, M., Carranza, E., & Villafuerte-Holguin, J.',
    abstract: 'Education Quarterly Reviews, 9(1), 1-11. ISSN 2621-5799.',
    publication_date: '2026-01-14',
    doi_link: 'https://doi.org/10.31014/aior.1993.09.01.615',
    pdf_file: 'https://www.asianinstituteofresearch.org/_files/ugd/ed8b62_d1890c5a4bd945e8adaf6cefbcac7299.pdf',
    type: 'article',
    category: 'regional',
    created: '2026-06-09T00:00:00Z',
    updated: '2026-07-09T00:00:00Z',
  },
  {
    id: 'pub_66',
    title: 'Comunicación asertiva y gamificación: docentes y el desarrollo psicomotor de niños con síndrome de Down (Assertive communication and gamification: instructors and the psychomotor development of children with Down syndrome)',
    authors: 'Villafuerte-Holguín, J., Pérez Plata, L., Bravo Loor, S., & Caycedo Casas, X.',
    abstract: 'Profesorado, Revista de Currículum y Formación del Profesorado, 29(2), julio 2025.',
    publication_date: '2025-07-01',
    doi_link: 'https://doi.org/10.30827/profesorado.v29i2.21315',
    type: 'article',
    category: 'impacto',
    created: '2026-06-09T00:00:00Z',
    updated: '2026-06-09T00:00:00Z',
  },
  {
    id: 'pub_67',
    title: 'Inclusive Education and the Use of Assistive Technologies: A Systematic Review',
    authors: 'Heredia-Solorzano, M., & Villafuerte-Holguin, J.',
    abstract: 'Education Quarterly Reviews, 8(2), 1-14. ISSN 2621-5799.',
    publication_date: '2025-05-01',
    doi_link: 'https://doi.org/10.31014/aior.1993.08.02.574',
    type: 'article',
    category: 'regional',
    created: '2026-06-09T00:00:00Z',
    updated: '2026-06-09T00:00:00Z',
  },
  {
    id: 'pub_68',
    title: 'Educational technology and teachers: effective teaching time in the classroom during the practicum',
    authors: 'Villafuerte Holguín, J. S., Intriago-Toala, E., Ramos-Zambrano, J., & Mena-Sánchez, L.',
    abstract: 'Sapienza: International Journal of Interdisciplinary Studies, 6(1), 2025.',
    publication_date: '2025-01-01',
    doi_link: 'https://doi.org/10.51798/sijis.v6i1.909',
    type: 'article',
    category: 'regional',
    created: '2026-06-09T00:00:00Z',
    updated: '2026-06-09T00:00:00Z',
  },
  {
    id: 'pub_69',
    title: 'Implementing Project-Based Learning in English Classes',
    authors: 'Abad, A., & Villafuerte-Holguin, J.',
    abstract: 'Education Quarterly Reviews, 8(3), 127-139. ISSN 2621-5799.',
    publication_date: '2025-09-01',
    doi_link: 'https://doi.org/10.31014/aior.1993.08.03.598',
    type: 'article',
    category: 'regional',
    created: '2026-06-09T00:00:00Z',
    updated: '2026-06-09T00:00:00Z',
  },
  {
    id: 'pub_70',
    title: 'Podcasting to sensitize gender equity in English language student teachers',
    authors: 'Guaranda Paredes, F. D., Palma Cedeño, N. N., & Villafuerte-Holguin, J.',
    abstract: 'Technium Education and Humanities, 12, 95-109.',
    publication_date: '2025-01-01',
    doi_link: 'https://doi.org/10.47577/teh.v12i.13404',
    type: 'article',
    category: 'regional',
    created: '2026-06-09T00:00:00Z',
    updated: '2026-06-09T00:00:00Z',
  },
  {
    id: 'pub_71',
    title: 'El tamaño de lo que sentimos',
    authors: 'Castillo Menéndez, A. F., Rodríguez Zambrano, A. D. & Cedeño Briones, M. J.',
    abstract: 'Libro ilustrado sobre el complejo de inferioridad. Ediciones ULEAM.',
    publication_date: '2026-06-01',
    pdf_file: '/files/DIPSB-PUB2026-024-El-tamano-de-lo-que-sentimos.pdf',
    cover_image: '/images/libro-el-tamano-de-lo-que-sentimos.png',
    type: 'book',
    category: 'libros',
    created: '2026-06-23T00:00:00Z',
    updated: '2026-06-23T00:00:00Z',
  },
  {
    id: 'pub_72',
    title: 'TikTok and English Language Learners Across age groups: A Bibliographic review',
    authors: 'Moreira Moreira, J. S., Orlando González, S. P., & Rodríguez Zambrano, A. D.',
    abstract: 'Revista Imaginario Social, 9(3).',
    publication_date: '2026-01-01',
    doi_link: 'https://doi.org/10.59155/is.v9i3.382',
    type: 'article',
    category: 'regional',
    created: '2026-07-04T00:00:00Z',
    updated: '2026-07-04T00:00:00Z',
  },
  {
    id: 'pub_73',
    title: 'Jugar, Idear y Escribir: Estrategias Lúdico-Creativas para Despertar la Escritura de Microcuentos en Educación General Básica',
    authors: 'González Macias, N. A., & Villafuerte Holguín, J.',
    abstract: 'Ciencia Latina Revista Multidisciplinar, 10(2). ISSN 2707-2207.',
    publication_date: '2026-06-14',
    doi_link: 'https://doi.org/10.37811/cl_rcm.v10i2.23826',
    type: 'article',
    category: 'regional',
    created: '2026-07-09T00:00:00Z',
    updated: '2026-07-09T00:00:00Z',
  },
  {
    id: 'pub_74',
    title: 'Condicionantes institucionales en el uso de tecnologías en el aula: Una aproximación desde el análisis multivariado',
    authors: 'Padrón Medina, A. M., Cordero, Y. N., Dueñas Espinoza, F. X., Domenech Polo, N. V., & Villafuerte Holguín, J.',
    abstract: 'Revista San Gregorio, 1(65), 22-31.',
    publication_date: '2026-01-01',
    doi_link: 'https://doi.org/10.36097/rsan.v1i65.3768',
    type: 'article',
    category: 'impacto',
    created: '2026-07-09T00:00:00Z',
    updated: '2026-07-09T00:00:00Z',
  },
];

export const videoCategories: VideoCategory[] = [
  {
    id: 'cat_1',
    name: 'Educa PINE',
    slug: 'educa-pine',
    description: 'Episodios del podcast Educa PINE sobre pedagogía e innovación educativa',
    order: 1,
    is_active: true,
    created: '2026-04-08T00:00:00Z',
    updated: '2026-04-08T00:00:00Z',
  },
  {
    id: 'cat_2',
    name: 'Voces Fuera del Aula',
    slug: 'voces-fuera-del-aula',
    description: 'Desafíos y experiencias en el aprendizaje — podcast Voces Fuera del Aula',
    order: 2,
    is_active: true,
    created: '2026-02-26T00:00:00Z',
    updated: '2026-02-26T00:00:00Z',
  },
  {
    id: 'cat_3',
    name: 'PsicoEducarte',
    slug: 'psicoeducarte',
    description: 'Programa PsicoEducarte — colaboración interdisciplinaria entre Psicología Educativa y el proyecto PINE',
    order: 3,
    is_active: true,
    created: '2026-06-05T00:00:00Z',
    updated: '2026-06-05T00:00:00Z',
  },
];

export const videos: Video[] = [
  {
    id: 'video_1',
    title: 'Adicción a las redes sociales',
    youtube_url: 'https://youtu.be/Ujmhwl-0Epk',
    description: 'Podcast Educa PINE — Episodio sobre la adicción a las redes sociales y su impacto en el contexto educativo. Producto de la cátedra de Investigación Educativa: Enfoques y Técnicas.',
    embed_id: 'Ujmhwl-0Epk',
    category: 'cat_1',
    published_date: '2026-04-08',
    order: 1,
    is_featured: true,
    tags: ['docencia'],
    created: '2026-04-08T00:00:00Z',
    updated: '2026-04-08T00:00:00Z',
  },
  {
    id: 'video_2',
    title: 'Comparaciones en las redes sociales',
    youtube_url: 'https://youtu.be/bZWv7zNWHUw',
    description: 'Podcast Educa PINE — Episodio sobre el efecto de las comparaciones sociales en plataformas digitales. Producto de la cátedra de Investigación Educativa: Enfoques y Técnicas.',
    embed_id: 'bZWv7zNWHUw',
    category: 'cat_1',
    published_date: '2026-04-08',
    order: 2,
    is_featured: true,
    tags: ['docencia'],
    created: '2026-04-08T00:00:00Z',
    updated: '2026-04-08T00:00:00Z',
  },
  {
    id: 'video_3',
    title: 'Ansiedad en las redes sociales',
    youtube_url: 'https://youtu.be/lZEHjvMxdE8',
    description: 'Podcast Educa PINE — Episodio sobre la ansiedad generada por el uso de redes sociales.',
    embed_id: 'lZEHjvMxdE8',
    category: 'cat_1',
    published_date: '2026-04-08',
    order: 3,
    is_featured: false,
    created: '2026-04-08T00:00:00Z',
    updated: '2026-04-08T00:00:00Z',
  },
  {
    id: 'video_4',
    title: 'Cursos vacacionales: ¿El propósito es realmente el aprendizaje?',
    youtube_url: 'https://youtu.be/XId0WxjAux0',
    description: 'Podcast Voces Fuera del Aula — Reflexión sobre la finalidad pedagógica de los cursos vacacionales.',
    embed_id: 'XId0WxjAux0',
    category: 'cat_2',
    published_date: '2026-02-26',
    order: 1,
    is_featured: true,
    created: '2026-02-26T00:00:00Z',
    updated: '2026-02-26T00:00:00Z',
  },
  {
    id: 'video_5',
    title: 'La procrastinación, el enemigo silencioso de nuestros sueños',
    youtube_url: 'https://youtu.be/firVFL67s04',
    description: 'Podcast Educa PINE — Episodio sobre la procrastinación y su impacto en el rendimiento académico y personal. Producto del proyecto de vinculación con la sociedad de la carrera de Pedagogía de Idiomas Nacionales y Extranjeros.',
    embed_id: 'firVFL67s04',
    category: 'cat_1',
    published_date: '2026-05-27',
    order: 4,
    is_featured: true,
    tags: ['vinculacion'],
    created: '2026-05-27T00:00:00Z',
    updated: '2026-05-27T00:00:00Z',
  },
  {
    id: 'video_6',
    title: 'PsicoEducarte | El Rol del Psicólogo Educativo',
    youtube_url: 'https://youtu.be/JFUN-l6fF98',
    description: 'PsicoEducarte — Contribución interdisciplinaria al proyecto PINE: el rol del psicólogo educativo en el contexto escolar.',
    embed_id: 'JFUN-l6fF98',
    category: 'cat_3',
    published_date: '2026-06-05',
    order: 1,
    is_featured: true,
    created: '2026-06-05T00:00:00Z',
    updated: '2026-06-05T00:00:00Z',
  },
  {
    id: 'video_7',
    title: 'EducaPine | Unknown things about Ecuador',
    youtube_url: 'https://youtu.be/qJO8F9lQYkE',
    description: 'Podcast Educa PINE — Producto de docencia: datos curiosos y poco conocidos sobre Ecuador.',
    embed_id: 'qJO8F9lQYkE',
    category: 'cat_1',
    published_date: '2026-06-04',
    order: 5,
    is_featured: false,
    tags: ['docencia'],
    created: '2026-06-04T00:00:00Z',
    updated: '2026-06-04T00:00:00Z',
  },
  {
    id: 'video_8',
    title: 'EducaPiNE | El temor al error: ¿Por qué nos callamos en clases?',
    youtube_url: 'https://youtu.be/sbkPClatf4M',
    description: 'Podcast Educa PINE — Episodio sobre el miedo a equivocarse y su efecto en la participación estudiantil. Producto del proyecto de vinculación con la sociedad de la carrera de Pedagogía de Idiomas Nacionales y Extranjeros.',
    embed_id: 'sbkPClatf4M',
    category: 'cat_1',
    published_date: '2026-06-02',
    order: 6,
    is_featured: false,
    tags: ['vinculacion'],
    created: '2026-06-02T00:00:00Z',
    updated: '2026-06-02T00:00:00Z',
  },
  {
    id: 'video_9',
    title: 'EDUCAPINE | Vinculación y experiencias de los estudiantes de PINE',
    youtube_url: 'https://youtu.be/Nj2TFVY7GFs',
    description: 'Podcast Educa PINE — Estudiantes de la carrera de Pedagogía de Idiomas Nacionales y Extranjeros comparten sus experiencias y reflexiones en el marco del proyecto de vinculación con la sociedad.',
    embed_id: 'Nj2TFVY7GFs',
    category: 'cat_1',
    published_date: '2026-06-23',
    order: 7,
    is_featured: false,
    tags: ['vinculacion'],
    created: '2026-06-23T00:00:00Z',
    updated: '2026-06-23T00:00:00Z',
  },
  {
    id: 'video_10',
    title: 'EducaPine | Innovación Educativa y las nuevas metodologías',
    youtube_url: 'https://youtu.be/DcH6yM8jaaU',
    description: 'Podcast Educa PINE — Episodio sobre innovación educativa y las nuevas metodologías de enseñanza-aprendizaje. Producto del proyecto de vinculación con la sociedad de la carrera de Pedagogía de Idiomas Nacionales y Extranjeros.',
    embed_id: 'DcH6yM8jaaU',
    category: 'cat_1',
    published_date: '2026-06-23',
    order: 8,
    is_featured: false,
    tags: ['vinculacion', 'innovacion'],
    created: '2026-06-23T00:00:00Z',
    updated: '2026-06-23T00:00:00Z',
  },
  {
    id: 'video_11',
    title: 'EducaPiNE | El tamaño de lo que sentimos',
    youtube_url: 'https://youtu.be/GhB8tWW1qoY',
    description: 'Podcast Educa PINE — Episodio dedicado al libro "El tamaño de lo que sentimos", publicado por miembros del proyecto en junio de 2026.',
    embed_id: 'GhB8tWW1qoY',
    category: 'cat_1',
    published_date: '2026-06-23',
    order: 9,
    is_featured: false,
    tags: ['libro', 'publicacion'],
    created: '2026-06-23T00:00:00Z',
    updated: '2026-06-23T00:00:00Z',
  },
  {
    id: 'video_12',
    title: 'Voces Fuera del Aula | Between reading and watching',
    youtube_url: 'https://youtu.be/35_g-1C6zHk',
    description: 'Podcast Voces Fuera del Aula — Episodio sobre lectura y medios audiovisuales en el aprendizaje.',
    embed_id: '35_g-1C6zHk',
    category: 'cat_2',
    published_date: '2026-06-24',
    order: 10,
    is_featured: false,
    tags: ['lectura', 'aprendizaje'],
    created: '2026-06-24T00:00:00Z',
    updated: '2026-06-24T00:00:00Z',
  },
  {
    id: 'video_13',
    title: 'EDUCAPINE | De ULEAM a Disney: Historias que transforman',
    youtube_url: 'https://youtu.be/97x9RMnVdMY',
    description: 'Podcast Educa PINE — Episodio sobre experiencias transformadoras de estudiantes de PINE, desde ULEAM hacia escenarios internacionales.',
    embed_id: '97x9RMnVdMY',
    category: 'cat_1',
    published_date: '2026-06-24',
    order: 11,
    is_featured: false,
    tags: ['vinculacion', 'internacionalizacion'],
    created: '2026-06-24T00:00:00Z',
    updated: '2026-06-24T00:00:00Z',
  },
  {
    id: 'video_14',
    title: 'Voces Fuera del Aula | ¿Es mejor muchos o pocos amigos?',
    youtube_url: 'https://youtu.be/oVvDY7nGv44',
    description: 'Podcast Voces Fuera del Aula — Episodio sobre la cantidad y calidad de las amistades en el contexto educativo.',
    embed_id: 'oVvDY7nGv44',
    category: 'cat_2',
    published_date: '2026-07-03',
    order: 13,
    is_featured: false,
    tags: ['amistad', 'reflexion'],
    created: '2026-07-03T00:00:00Z',
    updated: '2026-07-03T00:00:00Z',
  },
];

export const news: News[] = [
  {
    id: 'news_8',
    title: 'Capacitación en Redacción de Artículos Científicos para la carrera de Lengua y Literatura',
    content: 'Los docentes Jhonny Villafuerte y Arturo Rodríguez presentaron a la carrera de Lengua y Literatura sus experiencias y perspectivas sobre la redacción de artículos científicos, en el marco de una contribución del proyecto PINE realizada el 2 de julio de 2026.',
    featured_image: '/images/Capacitacion-RedaccionArticulos-02Julio.jpeg',
    published_date: '2026-07-02',
    is_featured: true,
    slug: 'capacitacion-redaccion-articulos-cientificos-lengua-literatura',
    created: '2026-07-02T00:00:00Z',
    updated: '2026-07-02T00:00:00Z',
  },
  {
    id: 'news_6',
    title: 'InterClass: Innovación Didáctica en Educación Inicial y Pedagogía de Idiomas',
    content: 'Una nueva InterClass reunió a las asignaturas de Innovación Didáctica en Educación Inicial, junto a la docente Lucy López Bermeo, y Pedagogía de Idiomas. Los estudiantes de Educación Inicial presentaron cuentos elaborados desde la asignatura de Literatura Infantil, compartiendo recursos didácticos creativos con sus compañeros de Pedagogía de Idiomas.',
    featured_image: '/images/InterClass-30Junio.jpeg',
    published_date: '2026-06-30',
    is_featured: true,
    slug: 'interclass-educacion-inicial-pedagogia-idiomas',
    created: '2026-06-30T00:00:00Z',
    updated: '2026-06-30T00:00:00Z',
  },
  {
    id: 'news_7',
    title: 'Socialización de Proyectos de Investigación, Vinculación y Tesis Doctorales',
    content: 'El miércoles 10 de junio, de 10h00 a 14h30, se realizó la socialización de proyectos de investigación y vinculación junto a tesis doctorales, con la participación de estudiantes, docentes y autoridades de la ULEAM. El evento reunió a representantes de distintas facultades para compartir avances y resultados de los proyectos en curso.',
    featured_image: '/images/Socializacion-Proyectos-10Junio.jpeg',
    published_date: '2026-06-10',
    is_featured: true,
    slug: 'socializacion-proyectos-investigacion-10junio',
    created: '2026-06-10T00:00:00Z',
    updated: '2026-06-10T00:00:00Z',
  },
  {
    id: 'news_5',
    title: '¡Nuevo libro publicado! "El tamaño de lo que sentimos"',
    content: 'El proyecto PINE celebra la publicación del libro ilustrado "El tamaño de lo que sentimos" — una obra sobre el complejo de inferioridad, escrita por Andy Fernando Castillo Menéndez, Arturo Damián Rodríguez Zambrano y Mikel Jarvin Cedeño Briones. Publicado en junio de 2026 por Ediciones ULEAM. Dos de sus autores son miembros activos de nuestro grupo de investigación.',
    featured_image: '/images/libro-el-tamano-de-lo-que-sentimos.png',
    published_date: '2026-06-23',
    is_featured: true,
    slug: 'libro-el-tamano-de-lo-que-sentimos',
    created: '2026-06-23T00:00:00Z',
    updated: '2026-06-23T00:00:00Z',
  },
  {
    id: 'news_4',
    title: 'Mes de la Magia: Trucos como Recurso Didáctico',
    content: 'En la próxima InterClass cada estudiante presentará un truco de magia como recurso didáctico innovador. Este reto surge del primer encuentro InterClass del proyecto, donde se trabajó el diagnóstico comunitario a través de un workshop debate. La magia como estrategia pedagógica invita a explorar la creatividad, la atención y el aprendizaje experiencial.',
    featured_image: '/images/InterClass.jpeg',
    published_date: '2026-06-02',
    is_featured: true,
    slug: 'mes-de-la-magia',
    created: '2026-06-02T00:00:00Z',
    updated: '2026-06-02T00:00:00Z',
  },
  {
    id: 'news_1',
    title: 'Inicio del Proyecto de Innovación Pedagógica',
    content: 'La ULEAM ha lanzado oficialmente el proyecto de innovaciones pedagógicas con el objetivo de transformar los procesos de enseñanza-aprendizaje en la institución. Este proyecto contará con la participación de docentes de diferentes facultades y la colaboración de universidades internacionales.',
    published_date: '2025-07-01',
    is_featured: true,
    slug: 'inicio-proyecto-innovacion',
    created: '2025-07-01T00:00:00Z',
    updated: '2025-07-01T00:00:00Z',
  },
  {
    id: 'news_3',
    title: 'Evento: Fomento de la Escritura Creativa en Innovaciones Pedagógicas',
    content: 'evento donde estudiantes y docentes universitarios y del colegio Juan Montalvo presentaron productos y estrategias de lectura creativa.',
    featured_image: '/images/IMG_20260428_131116_176.jpg',
    published_date: '2026-04-28',
    is_featured: false,
    slug: 'fomento-escritura-creativa',
    created: '2026-05-04T00:00:00Z',
    updated: '2026-05-04T00:00:00Z',
  },
];

export const activities: Activity[] = [
  {
    id: 'activity_1',
    title: 'Primer Taller de Podcast Educativo',
    description: 'Taller introductorio sobre la producción de podcasts educativos para la innovación pedagógica.',
    photos: ['/images/actividad_previa_podcast.jpeg'],
    event_date: '2025-02-15',
    category: 'taller',
    created: '2025-02-15T00:00:00Z',
    updated: '2025-02-15T00:00:00Z',
  },
  {
    id: 'activity_2',
    title: 'Grabación de Episodio Piloto',
    description: 'Primera grabación del podcast del proyecto con la participación del líder y co-líder.',
    photos: ['/images/Actividad_Podcast.jpeg'],
    event_date: '2025-03-01',
    category: 'grabacion',
    created: '2025-03-01T00:00:00Z',
    updated: '2025-03-01T00:00:00Z',
  },
  {
    id: 'activity_3',
    title: 'InterClass: Diagnóstico Comunitario y Workshop Debate',
    description: 'Clase innovadora entre varios cursos donde se abordó el diagnóstico comunitario mediante un workshop debate. Se anunció el Mes de la Magia: en la próxima InterClass cada estudiante presentará un truco de magia como recurso didáctico.',
    photos: ['/images/InterClass.jpeg'],
    event_date: '2026-06-02',
    category: 'interclass',
    created: '2026-06-02T00:00:00Z',
    updated: '2026-06-02T00:00:00Z',
  },
  {
    id: 'activity_4',
    title: 'InterClass: Innovación Didáctica en Educación Inicial y Pedagogía de Idiomas',
    description: 'Encuentro entre las asignaturas de Innovación Didáctica en Educación Inicial (docente Lucy López Bermeo) y Pedagogía de Idiomas. Estudiantes de Educación Inicial presentaron cuentos desde la asignatura de Literatura Infantil como recurso didáctico.',
    photos: ['/images/InterClass-30Junio.jpeg'],
    event_date: '2026-06-30',
    category: 'interclass',
    created: '2026-06-30T00:00:00Z',
    updated: '2026-06-30T00:00:00Z',
  },
];

export const siteSettings: SiteSettings[] = [
  {
    id: 'setting_1',
    key: 'facebook_url',
    value: 'https://facebook.com/uleam',
    section: 'social',
    created: '2025-01-01T00:00:00Z',
    updated: '2025-01-01T00:00:00Z',
  },
  {
    id: 'setting_2',
    key: 'twitter_url',
    value: 'https://twitter.com/uleam',
    section: 'social',
    created: '2025-01-01T00:00:00Z',
    updated: '2025-01-01T00:00:00Z',
  },
  {
    id: 'setting_3',
    key: 'instagram_url',
    value: 'https://instagram.com/uleam',
    section: 'social',
    created: '2025-01-01T00:00:00Z',
    updated: '2025-01-01T00:00:00Z',
  },
  {
    id: 'setting_4',
    key: 'youtube_url',
    value: 'https://youtube.com/@uleam',
    section: 'social',
    created: '2025-01-01T00:00:00Z',
    updated: '2025-01-01T00:00:00Z',
  },
  {
    id: 'setting_5',
    key: 'contact_email',
    value: 'innovacion@uleam.edu.ec',
    section: 'contact',
    created: '2025-01-01T00:00:00Z',
    updated: '2025-01-01T00:00:00Z',
  },
  {
    id: 'setting_6',
    key: 'institution_name',
    value: 'Universidad Laica Eloy Alfaro de Manabí (ULEAM)',
    section: 'general',
    created: '2025-01-01T00:00:00Z',
    updated: '2025-01-01T00:00:00Z',
  },
];

// Admin users configuration
export const adminUsers = [
  {
    id: 'admin_1',
    email: 'arturo.rodriguez@uleam.edu.ec',
    password: 'Pine2026',
    role: 'admin' as const,
  },
  {
    id: 'admin_2',
    email: 'jhonny.villafuerte@uleam.edu.ec',
    password: 'Pine2026',
    role: 'admin' as const,
  },
  {
    id: 'admin_3',
    email: 'german.carrera@uleam.edu.ec',
    password: 'Pine2026',
    role: 'admin' as const,
  },
  {
    id: 'admin_4',
    email: 'veronica.chavez@uleam.edu.ec',
    password: 'Pine2026',
    role: 'admin' as const,
  },
];
